/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    Greet: typeof import('./src/components/Greet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAvatar: typeof import('tdesign-mobile-vue')['Avatar']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TDivider: typeof import('tdesign-mobile-vue')['Divider']
    TIcon: typeof import('tdesign-mobile-vue')['Icon']
    TImage: typeof import('tdesign-mobile-vue')['Image']
    TImageViewer: typeof import('tdesign-mobile-vue')['ImageViewer']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TSearch: typeof import('tdesign-mobile-vue')['Search']
    TSwipe: typeof import('tdesign-mobile-vue')['Swipe']
    TSwiper: typeof import('tdesign-mobile-vue')['Swiper']
    TSwiperItem: typeof import('tdesign-mobile-vue')['SwiperItem']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
  }
}
